"""Threshold-gated email notification — only fires when something important happens."""

import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List

from ..models import ContentItem, NotificationConfig

logger = logging.getLogger(__name__)

EMOJIS = ["🔥", "⚡", "🎯", "🚀", "💡", "🧠", "⭐", "🔬", "🛠️", "📡"]


def send_notification(
    config: NotificationConfig,
    all_items: List[ContentItem],
    date: str,
) -> bool:
    """Send an email with items above notify_threshold. Silent if none qualify.

    Returns True if email was sent, False otherwise.
    """
    email_address = os.getenv(config.email_address_env, "")
    password = os.getenv(config.password_env, "")
    recipients_raw = os.getenv(config.recipients_env, "")
    recipients = [r.strip() for r in recipients_raw.split(",") if r.strip()]

    if not config.enabled or not recipients:
        return False

    if not password or not email_address:
        logger.warning("SMTP email or password env vars not set, skipping notification")
        return False

    hot = [i for i in all_items if (i.ai_score or 0) >= config.notify_threshold]
    if not hot:
        logger.info("No items above notify threshold — staying silent")
        return False

    rest_count = len(all_items) - len(hot)
    n = len(hot)
    count_word = f"{n} blip{'s' if n != 1 else ''}"

    # --- plain text ---
    text_lines = [f"{count_word} on the radar", ""]
    for i, item in enumerate(hot):
        emoji = EMOJIS[i % len(EMOJIS)]
        text_lines.append(f"{emoji} {item.title}")
        note = item.metadata.get("relevance") or item.ai_reason or ""
        if note:
            text_lines.append(f"   {note}")
        text_lines.append(f"   {item.url}")
        text_lines.append("")

    if rest_count > 0 and config.pages_url:
        text_lines.append(f"+ {rest_count} more: {config.pages_url}")
    elif config.pages_url:
        text_lines.append(f"Full briefing: {config.pages_url}")

    text_body = "\n".join(text_lines)

    # --- html ---
    items_html = ""
    for i, item in enumerate(hot):
        emoji = EMOJIS[i % len(EMOJIS)]
        note = item.metadata.get("relevance") or item.ai_reason or ""
        note_html = (
            f'<div style="color:#6b7280;font-size:13px;margin-top:2px;padding-left:28px">{note}</div>'
            if note else ""
        )
        items_html += f"""
        <div style="margin-bottom:20px">
            <div style="font-size:16px;line-height:1.4">{emoji} <a href="{item.url}" style="color:#1a1a1a;text-decoration:none;font-weight:600">{item.title}</a></div>
            {note_html}
        </div>"""

    footer_parts = []
    if rest_count > 0 and config.pages_url:
        footer_parts.append(
            f'<a href="{config.pages_url}" style="color:#2563eb;text-decoration:none">+ {rest_count} more in the full briefing &rarr;</a>'
        )
    elif config.pages_url:
        footer_parts.append(
            f'<a href="{config.pages_url}" style="color:#2563eb;text-decoration:none">Full briefing &rarr;</a>'
        )
    footer_html = "<br>".join(footer_parts)

    html_body = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:20px;color:#1a1a1a">
<div style="font-size:22px;margin-bottom:16px">&#128752; {count_word} on the radar</div>
{items_html}
<div style="margin-top:24px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:14px">
{footer_html}
</div>
<div style="margin-top:16px;font-size:12px;color:#d1d5db">auto-generated by your tech radar</div>
</body></html>"""

    subject = f"{count_word} on the radar"

    try:
        with smtplib.SMTP_SSL(config.smtp_server, config.smtp_port) as server:
            server.login(email_address, password)
            for recipient in recipients:
                msg = MIMEMultipart("alternative")
                msg["Subject"] = subject
                msg["From"] = f"Tech Radar <{email_address}>"
                msg["To"] = recipient
                msg.attach(MIMEText(text_body, "plain", "utf-8"))
                msg.attach(MIMEText(html_body, "html", "utf-8"))
                server.send_message(msg)
                logger.info(f"Notification sent to {recipient}")
        return True
    except Exception as e:
        logger.error(f"Notification failed: {e}")
        return False
